-- begin PRACTICE_BID
alter table PRACTICE_BID add constraint FK_PRACTICE_BID_ON_INITIATOR foreign key (INITIATOR_ID) references PRACTICE_INITIATOR(ID)^
alter table PRACTICE_BID add constraint FK_PRACTICE_BID_ON_EXECUTOR foreign key (EXECUTOR_ID) references PRACTICE_EXECUTOR(ID)^
create index IDX_PRACTICE_BID_ON_INITIATOR on PRACTICE_BID (INITIATOR_ID)^
create index IDX_PRACTICE_BID_ON_EXECUTOR on PRACTICE_BID (EXECUTOR_ID)^
-- end PRACTICE_BID
